### ISSUE TITLE
Default Branch 일부러 Page로 한건가요?

### ISSUE THREAD

**Issue by pec9399** [18-1-SKKU-OSS/2018-1-OSS-L3#12]

**Comment by WraithL** [comment]
음 정적페이지 소스 그냥 올리면 좋을것 같아서??
master에도 hexo config 파일만 있길래 바꿔놨어요
README 파일만 복사해서 올려줄 수 있나

**Comment by pec9399** [comment]
branch 합쳤고 일단 docs 안에 대진이가 하던 config 파일도 같이 넣어놨어요
