### ISSUE TITLE
Eslint Application For Demo Pages

### ISSUE THREAD

**Issue by pec9399** [18-1-SKKU-OSS/2018-1-OSS-L3#2]
The demo pages does not follow the linting guide provided on the official documentations (eslint-ignored).

**Comment by WraithL** [comment]
![eslint problem](https://user-images.githubusercontent.com/22650521/40695107-9c631a7a-63fa-11e8-99f2-5f3643db0260.png)
Too many errors...

**Comment by WraithL** [comment]
![image](https://user-images.githubusercontent.com/22650521/40700076-e41af0f0-6412-11e8-8d3a-81b38e263763.png)
eslint로 린트 돌려봤는데 딱히 문제되는게 없네요

**Comment by pec9399** [comment]
데모 페이지 eslint-ignore 되있어서 그런거 아닌가요?

**Comment by pec9399** [comment]
그거 에러 lint 에서 자동으로 고쳐주는거 돌릴 수 있을 텐대

**Comment by WraithL** [comment]
파일 하나하나 돌리면 에러 나네요
