### ISSUE TITLE
Some graph api

### ISSUE THREAD

**Issue by WraithL** [18-1-SKKU-OSS/2018-1-OSS-L3#3]
Does billboard.js have some graph api  like this?
 
![image](https://user-images.githubusercontent.com/22650521/40652790-37ac2e0e-6374-11e8-951e-2590b9f7559a.png)
![image](https://user-images.githubusercontent.com/22650521/40652918-a0cf8c82-6374-11e8-82ca-794fdc6382dd.png)

**Comment by pec9399** [comment]
좋은데 거기서 영어로만 받아줄 것 같아요 ㅎㅎ

**Comment by pec9399** [comment]
CONTRIBUTING doc 참고하셔서 pull request 날리셔야 될 것 같습니다
